---
title: "Ida Wells Egonetzwerk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Suffragetten - Ida Wells"
subtitle: "Ego-Netzwerk"
author: "Niclas Reichelt, Lisa Pham, Karla Denzer, Penelope Hoeth, Daniel Guib, Sarah Huß"
date: '08.03.2021'
output: html_notebook
---

Github: <https://github.com/NiclasReichelt/Ida-Wells>

Codebuch: <https://github.com/NiclasReichelt/Ida-Wells/blob/main/Ida%20Wells%20-%20Ego%20-%20Codebuch.csv>

## Gesamtnetzwerk

```{r}

library(tidyverse)
library(igraph)

# Einlesen der Edge- und Nodelist
el <- read.csv("https://raw.githubusercontent.com/NiclasReichelt/Ida-Wells/main/Ida%20Wells%20-%20Ego%20-%20Finale%20-%20Edgelist.csv", header=T, as.is=T, sep = ",")

nodes <- read.csv("https://raw.githubusercontent.com/NiclasReichelt/Ida-Wells/main/Ida%20Wells%20-%20Ego%20-%20Finale%20-%20Nodelist.csv", header=T, as.is=T, sep = ",")

# Matrix erstellen
edgematrix <-as.matrix(el)

# Zusammenführen von Edge- und Nodelist als igraph-Objekt
Ida <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=F)

#Gesamtnetzwerk erstellen

V(Ida) [V(Ida)$type == 1] $shape <- "circle"
V(Ida) [V(Ida)$type == 2] $shape <- "square"
V(Ida) [V(Ida)$type == 2] $color <- "orange"

V(Ida) [V(Ida)$sex == 2] $shape <- "rectangle"
V(Ida) [V(Ida)$sex == 3] $shape <- "rectangle"


V(Ida) [V(Ida)$type == 1] $frame.color = NA
V(Ida) [V(Ida)$type == 1] $frame.color = NA 

V(Ida) [V(Ida)$skincolor == 1] $color <- "lightblue"
V(Ida) [V(Ida)$skincolor == 2] $color <- "lightgreen"
V(Ida) [V(Ida)$skincolor == 3] $color <- "red"

V(Ida) [V(Ida)$power == 1] $size <- 5
V(Ida) [V(Ida)$power == 2] $size <- 10
V(Ida) [V(Ida)$power == 3] $size <- 15

edge.attributes(Ida)$weight



Ida
plot(Ida,
     layout=layout_with_kk,
     main="Ida Wells Egonetzwerk",
     edge.color="grey40",
     edge.curved=.8,
     edge.arrow.size=.8)

plot(Ida,
     asp=0, 
     layout=layout_with_kk,
     edge.arrow.size=.5,
     main ="Übersicht Gesamtnetzwerk")
```

## Teilnetzwerke

```{r Teilnetzwerke}

#Teilnetzwerke Allgemein

list.edge.attributes(Ida)
edge.attributes(Ida)$country

Ida_person <- delete.vertices(Ida, V(Ida) [type==2])

Ida_orga <- delete.vertices(Ida, V(Ida) [type==1])

#Teilnetzwerk USA


Ida_USA <- subgraph.edges(Ida, E(Ida)[country==1])

Ida_USA2 <- delete.vertices(Ida_USA, degree(Ida_USA)==0)


plot(Ida_USA2, layout=layout_with_fr,
     main="USA",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

#Teilnetzwerk GB

Ida_GB <- subgraph.edges(Ida, E(Ida)[country==2])

Ida_GB2 <- delete.vertices(Ida_GB, degree(Ida_GB)==0)

plot(Ida_GB2, layout=layout_with_fr,
     main="Großbritannien",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

#Nebeneinander

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_GB, edge.arrow.size=.3, main="GB")
plot(Ida_USA, edge.arrow.size=.3,  main="USA")
```
```{r}
#Unterteilung

#Unterteilung weiblich & männlich

Ida_male <- delete.vertices(Ida, V(Ida) [sex==2])
Ida_female <- delete.vertices(Ida, V(Ida) [sex==1])

#Unterteilung schwarz & weiss

Ida_black <- delete.vertices(Ida, V(Ida) [skincolor==2])
Ida_white <- delete.vertices(Ida, V(Ida) [skincolor==1])

```


```{r fig.height=14, 5, fig.width=24}

#Teilnetzwerke Unterstützer

Ida_sup <- subgraph.edges(Ida, E(Ida)[relation==2])

Ida_male_sup <- subgraph.edges(Ida_male, E(Ida_male)[relation==2])

Ida_female_sup <- subgraph.edges(Ida_female, E(Ida_female)[relation==2])

Ida_black_sup <- subgraph.edges(Ida_black, E(Ida_black)[relation==2])

Ida_white_sup <- subgraph.edges(Ida_white, E(Ida_white)[relation==2])

#plotting

plot(Ida_male_sup, layout=layout_with_kk,
     main="männliche Unterstützer",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_female_sup, layout=layout_with_kk,
     main="weibliche Unterstützer",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_black_sup, layout=layout_with_kk,
     main="schwarze Unterstützer",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_white_sup, layout=layout_with_kk,
     main="weisse Unterstützer",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

#Nebeneinander

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_white_sup, edge.arrow.size=.3, main="schwarze Unterstützer")
plot(Ida_black_sup, edge.arrow.size=.3,  main="weiße Unterstützer")
```



```{r}
#Teilnetzwerke Geschäftliche Beziehung

Ida_bus <- subgraph.edges(Ida, E(Ida)[relation==4])

Ida_male_bus <- subgraph.edges(Ida_male, E(Ida_male)[relation==4])
Ida_female_bus <- subgraph.edges(Ida_female, E(Ida_female)[relation==4])

Ida_black_bus <- subgraph.edges(Ida_white, E(Ida_white)[relation==4])
Ida_white_bus <- subgraph.edges(Ida_black, E(Ida_black)[relation==4])



#plotting

Ida_male_bus
Ida_female_bus
Ida_black_bus
Ida_white_bus

plot(Ida_male_bus, layout=layout_with_kk,
     main="männliche Geschäftsbzeihungen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_female_bus, layout=layout_with_kk,
     main="weibliche Geschäftsbeziehungen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_black_bus, layout=layout_with_kk,
     main="Geschäftsbeziehungen mit Schwarzen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_white_bus, layout=layout_with_kk,
     main="Geschäftsbeziehungen mit Weissen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")


```

```{r}

#Teilnetzwerk nach Aufgabenbereich

Ida_jour <- delete.vertices(Ida, V(Ida) [Journalismus==0])

Ida_act <- delete.vertices(Ida, V(Ida) [Aktivismus==0])

Ida_pol <- delete.vertices(Ida, V(Ida) [Politik==0])

Ida_jour_act <- delete.vertices(Ida_jour, V(Ida_jour)[Aktivismus==0])

#plotting

plot(Ida_jour, layout=layout_with_kk,
     main="Beziehungen zu Journalisten",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_act, layout=layout_with_kk,
     main="Beziehungen zu Aktivisten",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_pol, layout=layout_with_kk,
     main="Beziehungen zu Politikern",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_jour_act, layout=layout_with_kk,
     main="Beziehungen zu aktivistischen Journalisten",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

#Nebeneinander

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_jour, edge.arrow.size=.3, main="Journalisten")
plot(Ida_act, edge.arrow.size=.3,  main="Aktivisten")
plot(Ida_pol, edge.arrow.size=.3,  main="Politiker")

        


```

```{r}

#Teilnetzwerk nach Motivation

Ida_mot <- delete.vertices(Ida, V(Ida) [type==2])

Ida_mot_both <- delete.vertices(Ida_mot, V(Ida_mot) [motivation==0])
Ida_mot_both1 <- delete.vertices(Ida_mot_both, V(Ida_mot_both) [motivation==4])
Ida_mot_both2 <- delete.vertices(Ida_mot_both1, V(Ida_mot_both1) [motivation==1])
Ida_mot_both3 <- delete.vertices(Ida_mot_both2, V(Ida_mot_both2) [motivation==2])


Ida_mot_black <- delete.vertices(Ida_mot_both1, V(Ida_mot_both1) [motivation==2])


Ida_mot_woman <- delete.vertices(Ida_mot_both1, V(Ida_mot_both1) [motivation==1])

#plotting

plot(Ida_mot_black, layout=layout_with_kk,
     main="Einsatz für Rechte von Schwarzen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_mot_woman, layout=layout_with_kk,
     main="Einsatz für Rechte von Frauen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_mot_both3, layout=layout_with_kk,
     main="Einsatz für Rechte von Schwarzen und Frauen",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

#Nebeneinander

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_mot_black, edge.arrow.size=.3, main="Schwarzenrechtler")
plot(Ida_mot_woman, edge.arrow.size=.3,  main="Frauenrechtler")
plot(Ida_mot_both2, edge.arrow.size=.3,  main="Beides")

```
```{r}

#Teilnetzwerk nach Zeit (vor und nach GB)

Ida_afterGB <- subgraph.edges(Ida, E(Ida)[timeperiod==5])

Ida_beforeGB <- delete.edges(Ida, E(Ida) [timeperiod==3])
Ida_beforeGB1 <- delete.edges(Ida_beforeGB, E(Ida_beforeGB) [timeperiod==4])
Ida_beforeGB2 <- delete.edges(Ida_beforeGB1, E(Ida_beforeGB1) [timeperiod==5])

#ohne Personen

Ida_afterGB_orga <- subgraph.edges(Ida_orga, E(Ida_orga)[timeperiod==5])

Ida_beforeGB_orga <- delete.edges(Ida, E(Ida) [timeperiod==3])
Ida_beforeGB_orga1 <- delete.edges(Ida_beforeGB_orga, E(Ida_beforeGB_orga) [timeperiod==4])
Ida_beforeGB_orga2 <- delete.edges(Ida_beforeGB_orga1, E(Ida_beforeGB_orga1) [timeperiod==5])



#plotting

plot(Ida_beforeGB2, layout=layout_with_kk,
     main="Netzwerk vor GB-Reise",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_afterGB, layout=layout_with_kk,
     main="Netzwerk nach GB-Reise",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_afterGB_orga, layout=layout_with_kk,
     main="Orga-Netzwerk vor GB-Reise",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")

plot(Ida_beforeGB_orga2, layout=layout_with_kk,
     main="Orga-Netzwerk nach GB-Reise",
     edge.arrow.size=.7,
     edge.width=E(Ida)$weight,
     edge.color="black")



#Nebeneinander

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_beforeGB2, edge.arrow.size=.3, main="Schwarzenrechtler")
plot(Ida_afterGB, edge.arrow.size=.3,  main="Frauenrechtler")

#Nebeneinander2

par(mfrow=c(1,3), mar=c(0,0,1,2))
plot(Ida_afterGB_orga, edge.arrow.size=.3,  main="Beides")
plot(Ida_beforeGB_orga2, edge.arrow.size=.3,  main="Beides")


```
